### ISSUE TITLE
nRF52840 Dongle

### ISSUE THREAD

**Issue by blademckain** [bluekitchen/raccoon#1]
hi, is it possible to install your firmware on an nRF52840 Dongle to sniff ble tags nearby?
after uploading your firmware is it possible to use the nRF52840 Dongle via the linux hcitool command?

**Comment by mringwal** [comment]
You can receive BLE Advertisements using raccoon. The current firmware does not support USB, so you'd need to connect a FTDI 232R or similar to use it on the nRF52840 USB Dongle. It uses a data format similar to PCAP, which is different from HCI.

Alternatively, you can install the hci_usb firmware from Zephyr project and use it with linux hcitool.
