### ISSUE TITLE
pca10059 don't restart sniffing after following a connection

### ISSUE THREAD

**Issue by SeanBurford** [bluekitchen/raccoon#11]
After following a connection, the LED on the pca10059 doesn't start flashing again.

Looking at raccoon.py, the restart CMD_SNIFF_CHANNEL only sends a 19 byte payload, compared to the 20 byte payload during initial setup.  It omits the min RSSI value.  Increasing this packet to 20 bytes and providing the same min RSSI value results in happy LEDs and, by the look of things, ongoing packet capture.

**Comment by mringwal** [comment]
Fixed by your PR.
