### ISSUE TITLE
nRF52840 stuck in Bootloader after flashing

### ISSUE THREAD

**Issue by cyb3rwr3ck** [bluekitchen/raccoon#8]
Hi there, 
I've flashed the hex file successfully following the README using nrfConnect but the dongle still loads the bootloader (pulsing red LED), not the application, although it reports that the  programmer found an application after reseting the dongle by replugging it. Also I can see that there is an application present via the GUI. 
Any idea what is going on here?
Thx

**Comment by mringwal** [comment]
hi. hard to tell. did the compile work right away?

if you have, you can try on a different device and/or to flash on a different computer/OS. 

After flashing the firmware, it doesn't blink for me anymore.

**Comment by cyb3rwr3ck** [comment]
it was my fault. I flashed the hex file from the _nrf52840_mdk_usb_dongle_ not from the _pca10059_ folder. Obviously I was distracted by the name of the folder and missed the _mdk_ part of it :-(
