### ISSUE TITLE
not seeing connections

### ISSUE THREAD

**Issue by telethonic** [bluekitchen/raccoon#9]
Hi,

Thanks for providing such a great tool :-)

I'm using the makerdiary nRF52840 MDK USB dongle, replaced the UF2 bootloader
with the Open bootloader, and wrote nrf52840_xxaa.hex to it using nRF Connect.

My config.py:

```sniffers = [
   { 'port':'/dev/ttyACM0', 'baud':1000000, 'rtscts':1 }
]
```

Some sample output (addresses edited a bit):

```meltdown :raccoon-master/pyclient#14 -> ./raccoon.py  --addr f3:ca:88:12:34:56
[+] Config: output trace.pcap (pcap), min rssi -80 dBm- filter: f3:ca:88:12:34:56
[-] Sniffer #0: port /dev/ttyACM0, baud 1000000, rtscts 1, channel 37, version 
[+]  1. 5a:96:8b:00:00:00         ADV_IND  -49 dBm, 
[+]  2. f3:ca:88:12:34:56         ADV_IND  -54 dBm, Name: 'KL-TNS-882fd11b'
[+]  3. 54:a2:0a:00:00:00         ADV_IND  -53 dBm, 
[+]  4. f3:ca:88:12:34:56        SCAN_RSP  -53 dBm, UUID16: 0001
[+]  5. 54:a2:0a:00:00:00        SCAN_RSP  -53 dBm, 
[+]  6. 5a:96:8b:00:00:00        SCAN_RSP  -41 dBm, 
[+]  7. 74:34:34:00:00:00    ADV_SCAN_IND  -80 dBm, UUID16: FE9F
[+]  8. 74:34:34:00:00:00        SCAN_RSP  -80 dBm, 
[+] 
Thanks for using raccoon.
```

The f3:ca:88 device is a motion sensor. I connect to it using an iPhone app,
but the connection is not captured. Do you have any idea what could be the issue?

Thanks :-)

**Comment by mringwal** [comment]
hi.. advertisements are sent on all three advertising channels. You need to listen to the one on which the Central will connect to. You can configure raccoon to listen on 38 or 39 and try again a few times. Alternatively, the Peripheral can advertise only on one channel, or, you can use 3 devices with Raccoon.
